CREATE DATABASE gtg_db;
CREATE DATABASE walking_db;
CREATE DATABASE qigong_db;

\c postgres

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE SCHEMA IF NOT EXISTS auth;
CREATE SCHEMA IF NOT EXISTS storage;

GRANT ALL PRIVILEGES ON DATABASE gtg_db TO postgres;
GRANT ALL PRIVILEGES ON DATABASE walking_db TO postgres;
GRANT ALL PRIVILEGES ON DATABASE qigong_db TO postgres;